// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBczvduV4sl_j2dwzWZc5sRu_CqaqEF6Fo',
    appId: '1:35477186972:web:44fc32963f173483eec059',
    messagingSenderId: '35477186972',
    projectId: 'inventario-x',
    authDomain: 'inventario-x.firebaseapp.com',
    storageBucket: 'inventario-x.firebasestorage.app',
    measurementId: 'G-3DJ638J520',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAamudN51I8V5mrwjvkkyO8J8mz9syube0',
    appId: '1:35477186972:android:05463398f9baf57aeec059',
    messagingSenderId: '35477186972',
    projectId: 'inventario-x',
    storageBucket: 'inventario-x.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEDC2SqrCLrMVMipWrmzWyoSG8c_URVeA',
    appId: '1:35477186972:ios:816a59b239e94761eec059',
    messagingSenderId: '35477186972',
    projectId: 'inventario-x',
    storageBucket: 'inventario-x.firebasestorage.app',
    iosBundleId: 'com.example.flutterProducts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEDC2SqrCLrMVMipWrmzWyoSG8c_URVeA',
    appId: '1:35477186972:ios:816a59b239e94761eec059',
    messagingSenderId: '35477186972',
    projectId: 'inventario-x',
    storageBucket: 'inventario-x.firebasestorage.app',
    iosBundleId: 'com.example.flutterProducts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBczvduV4sl_j2dwzWZc5sRu_CqaqEF6Fo',
    appId: '1:35477186972:web:cd57df05487b5376eec059',
    messagingSenderId: '35477186972',
    projectId: 'inventario-x',
    authDomain: 'inventario-x.firebaseapp.com',
    storageBucket: 'inventario-x.firebasestorage.app',
    measurementId: 'G-P59CT4MBBZ',
  );
}
